### PR TITLE
Use referencehub instead of nickname when getting player

### PR DESCRIPTION
**Pull request by PintTheDragon**
Why are you even using the nickname when you have much better info on the player?

Anyway, just think about the funny thing that happens when 2 players with the same nickname join and the one later in the list runs `tut` and the first one is made a tutorial because the nickname is used. Yeah this fixes that.

### CODE REVIEW

**Comment by ThatsDekuu** [comment]
Just use **SenderId** or **ReferenceHub** instead of **Player.Get(((CommandSender)sender).Nickname)**

**Comment by PintTheDragon** [comment]
@ThatsDekuu that's uhh...

That's literally what this PR is.

**Comment by thomasjosif** [comment]
> Why are you even using the nickname when you have much better info on the player?
Question for KoukoCocoa (the previous maintainer) not sure why he did it like that :)

And @ThatsDekuu stating the obvious in a PR that's already fixing something is really strange...

**Comment by thomasjosif** [comment]
Oh, and next time @PintTheDragon make sure it compiles or doesn't error out before PRing. 

image

**Pull request merged**
